### ISSUE TITLE
getGSE122425: use layers for storing multiple assays

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/BioPlexPy#1]
Looking at the code of [getGSE122425](https://github.com/ccb-hms/BioPlexPy/blob/73a0747224e37ff4c3464dc4415908a3610b82d5/BioPlexPy/helper_funcs.py#L84), I believe we can make use of [layers](https://anndata.readthedocs.io/en/stable/anndata.AnnData.layers.html) to store the raw counts matrix and the FPKM matrix in a single `AnnData` object. This would in turn allow `getGSE122425` to return a single `AnnData` object.

**Comment by vargasr39** [comment]
Was able to use layers to add the RPKM matrix in the same AnnData object as the raw counts matrix, updated in the function and now returns just one AnnData object.

**Comment by lgeistlinger** [comment]
Very nice!
