### ISSUE TITLE
permutation test: allow for set of uniprot IDs as input

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/BioPlexPy#16]
BioPlexPy's `permutation_test_for_CORUM_complex` function implements testing overlaps of PPIs with a complex of interest based on random sampling. The function samples random subnetworks from the given PPI network, matching the number of subunits and the bait:prey ratio of the complex being tested.

This testing strategy can be generalized to other gene or protein sets, and as discussed with Ed, a useful enhancement of this function would be to create a new generalized function that allows a set of uniprot IDs as input, eg representing a pathway of interest or a list of proteins associated with a certain disease phenotype of interest.

**Comment by vargasr39** [comment]
replaced function `permutation_test_for_CORUM_complex` with function `permutation_test_for_uniprot_list` which takes in a list of uniprot IDs and carries out permutation test on this set.

Updated function in function scripts, init file, TESTING notebook & docs Examples notebook to reflect change to function input. Permutation test for CORUM complexes can still be performed with one additional line of code to retrieve the list of uniprot IDs from a specific CORUM complex then using that list as input into updated function (see Examples notebook).
