### ISSUE TITLE
permutation test: account for node degree

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/BioPlexPy#17]
Hi @vargasr39 - one thing that we discussed with Ed and that also came up as a reviewer comment for the application note is to, optionally, account for the node degree distribution in the complex being tested. That means in addition to accounting for the bait:prey ratio in the complex, we would like to pull out in each random sample the same amount of baits and same amount of preys, but also pull out nodes in a way that we have node degrees as in the complex that we test.

A simple example: if we would have a complex of two baits and one prey protein, and overall the first bait has 3 edges, the second bait has 2 edges, and the prey has one edge, than we would like to pull in each random sample a bait with 3 edges, a bait with 2 edges, and a prey with one edge. (an enhancement to this would be to account for directionality, ie incoming node degree and outgoing node degree, but I would ignore that for the first time around).

This should be a boolean argument to the function, ie something like `preserve.node.degree = FALSE` to perform the test as it is right now, ie without accounting for node degree, and something like `preserve.node.degree = TRUE` to account for node degree as described above.

**Comment by vargasr39** [comment]
This functionality has been implemented into the permutation_test_for_uniprot_list() function.
