### ISSUE TITLE
add small tutorial

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/BioPlexPy#6]
A small jupyter notebook illustrating how to invoke some of the key functions of the package and exploring the anatomy of the data structures and the data contents would be very helpful. I believe this could largely be modeled after the [data import/representation vignette](https://bioconductor.org/packages/release/bioc/vignettes/BioPlex/inst/doc/BioPlex.html) of the R package. One question is what is the right place of where to put this tutorial, does this belong somewhere in the package or in another repo?

**Comment by vargasr39** [comment]
Jupyter Notebook that demonstrates some of the functionality of the module has been added to the repo - we can add to it as we add to the module.
